name: Start RDP Server on Windows

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-2022

    steps:
    - name: Download and setup ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive -Path "ngrok.zip" -DestinationPath "$PWD\ngrok"
        Move-Item -Path "$PWD\ngrok\ngrok.exe" -Destination "C:\ngrok.exe"

    - name: Authenticate ngrok
      run: C:\ngrok.exe ngrok config add-authtoken 30hY01LGufTwLxNWo9dMpoRn7X9_59rfm4ctVQzWD7c3S4Tj1

    - name: Enable Remote Desktop and Firewall Rules
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start ngrok TCP tunnel on port 3389
      run: Start-Process -NoNewWindow -FilePath "C:\ngrok.exe" -ArgumentList "tcp 3389"

    - name: Wait and get public RDP address
      run: |
        Start-Sleep -Seconds 20
        $tunnel = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels"
        $rdpAddress = $tunnel.tunnels[0].public_url
        $cleaned = $rdpAddress -replace "tcp://", ""
        echo "RDP Address (host:port): $cleaned"
        "$cleaned" | Out-File -FilePath "rdp.txt" -Encoding utf8

    - name: Upload RDP address as artifact
      uses: actions/upload-artifact@v4
      with:
        name: RDP_Address
        path: rdp.txt
