name: TOOLBOXLAP

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository files
        uses: actions/checkout@v4

      - name: Download and install essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
        shell: pwsh

      - name: Check if show.bat exists
        run: |
          if exist show.bat (
            echo "show.bat found"
          ) else (
            echo "show.bat not found!" && exit 1
          )
        shell: cmd

      - name: Run show.bat (show website)
        run: show.bat
        shell: cmd

      - name: Run loop.bat (time counter)
        run: loop.bat
        shell: cmd
